name: Build and Package - Linux

on: [push, pull_request]

jobs:
  build-hnsd:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout hnsd repository
        uses: actions/checkout@v3
        with:
          repository: 'handshake-org/hnsd'

      - name: Install dependencies
        run: sudo apt install -y libunbound-dev

      - name: Build hnsd
        run: |
          ./autogen.sh && ./configure && make
          ls -l

      - name: Store hnsd binary
        uses: actions/upload-artifact@v3
        with:
          name: hnsd-bin
          path: ./hnsd

  build-fingertip:
    needs: build-hnsd
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          cache: true # Cache go modules

      - name: Install dependencies
        run: sudo apt install -y libgtk-3-dev libappindicator3-dev libunbound-dev

      - name: Build fingertip
        run: |
          go build -trimpath -o ./builds/linux/appdir/usr/bin
          ls -l builds/linux/appdir/usr/bin/

      - name: Download hnsd binary
        uses: actions/download-artifact@v3
        with:
          name: hnsd-bin
          path: builds/linux/appdir/usr/bin

      - name: Package as AppImage
        working-directory: ./builds/linux
        run: |
          ls -l appdir/usr/bin/
          chmod +x appdir/usr/bin/hnsd
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/fingertip.desktop -appimage -executable=appdir/usr/bin/hnsd

      - name: Store fingertip binary
        uses: actions/upload-artifact@v3
        with:
          name: fingertip-bin
          path: ./builds/linux/appdir/usr/bin/fingertip

      - name: Store fingertip appimage
        uses: actions/upload-artifact@v3
        with:
          name: fingertip-appimage
          path: ./builds/linux/Fingertip*.AppImage
